{{- if .Values.ingress.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.externalDomain }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - "{{ .Values.ingress.certificate.host | default .Values.externalDomain }}"
  secretName: {{ .Values.externalDomain }}
  issuerRef:
    name: {{ .Values.ingress.certificate.issuer }}
    kind: ClusterIssuer
{{- end }}
