kind: ConfigMap
apiVersion: v1
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    window.owntracks = window.owntracks || {};
    window.owntracks.config = {
      {{ .Values.frontend.config | toJson | trimSuffix "}" | trimPrefix "{" }},
      {{ .Values.frontend.jsConfig | indent 6 }}  
    };
