{{- if .Values.owntracks.service.enabled -}}
apiVersion: v1
kind: Service
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: "{{ $fullname }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.owntracks.service.type }}
  ports:
  - port: {{ .Values.owntracks.service.externalPort | default .Values.owntracks.service.port }}
    targetPort: {{ .Values.owntracks.service.port }}
    protocol: TCP
    name: http
  selector:
    app: "{{ $fullname }}"
{{- end -}}
