# You can chose to run this as a Deployment
# or a StatefulSet
kind: StatefulSet

image:
  name: eclipse-mosquitto
  version: 2.0.14-openssl
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

  port: 1883
  securePort: 8883

  externalPort: ""
  externalSecurePort: ""

config:
  enableInsecure: false
  enableSecure: true

  acl:
    anonymous:
    - matchType: pattern
      accessType: deny
      value: "+"
    users: {}

  authentication:
    enabled: true
    allowAnonymous: false

    users: {}

    # The secret has to contain a key "pwfile"
    usersSecret: ""

  persistence:
    enabled: false

    existingClaim: ""

    pvc:
      enabled: false
      storageClass: ""
      size: 1Gi

  tls:
    cafile: ""
    certfile: ""
    keyfile: ""

    existingSecret: ""

resources: {}

# additionalPodLabels:
