apiVersion: v2
name: owntracks
appVersion: 0.8.6-12
version: 0.0.1
type: application
home: https://github.com/dasbaumwolltier/helm-charts

dependencies:
  - name: mosquitto
    repository: https://k8s-at-home.com/charts/
    version: 4.3.2
    condition: mosquitto.enabled
    import-values:
      - "mosquitto"

