# Example: owntracks.example.com
externalDomain: ""
clusterDomain: "cluster.local"

owntracks:
  image:
    name: owntracks/recorder
    version: 0.8.6-12
    pullpolicy: IfNotPresent

  replicaCount: 1

  service:
    enabled: true

    port: 8083
    type: ClusterIP
    externalPort: ""

  persitence:
    enabled: false
    storageClass: "-"
    size: 10Gi
    existingClaim: ""

  lmdb:
    # The size of the database in MiB
    size: 10

  resources: {}

frontend:
  enabled: true

  image:
    name: owntracks/frontend
    version: 2.11.0
    pullpolicy: IfNotPresent
  
  service:
    enabled: true

    port: 8080
    type: ClusterIP
    externalPort: ""

  # For more options consult https://github.com/owntracks/frontend/blob/main/docs/config.md
  config:
    api:
      # The external base URL. For example https://owntracks.example.com
      baseUrl: ""

    verbose: false

  jsConfig: |
    endDateTime: (() => {
      const endDateTime = new Date();
      endDateTime.setHours(23, 59, 59, 0);
      return endDateTime;
    })(),

    // Data will be fetched from the first day of the current month
    startDateTime: (() => {
      const startDateTime = new Date();
      startDateTime.setHours(0, 0, 0, 0);
      startDateTime.setDate(1);
      return startDateTime;
    })(),

  replicaCount: 1

  resources: {}

ingress:
  enabled: false

  nginx: false
  annotations: {}

mqtt:
  enabled: false

  host: ""
  port: 1883
  user: ""
  password: ""

  userSecret: ""

  topics: []

# Values can be found here 
mosquitto:
  enabled: false

  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    # -- image repository
    repository: eclipse-mosquitto
    # -- image tag
    tag: 2.0.11
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- Configures service settings for the chart. Normally this does not need to be modified.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          enabled: false
        mqtt:
          enabled: true
          port: 1883

  auth:
    # -- By enabling this, `allow_anonymous` gets set to `false` in the mosquitto config.
    enabled: false

  persistence:
    # -- Configure a persistent volume to place mosquitto data in.
    # When enabled, this enables `persistence` and `persistence_location` in the mosquitto config.
    # @default -- See values.yaml
    data:
      enabled: false
      mountPath: /mosquitto/data
    # -- Configure a persistent volume to place *.conf mosquitto-config-files in.
    # When enabled, this gets set as `include_dir` in the mosquitto config.
    # @default -- See values.yaml
    configinc:
      enabled: false
      mountPath: /mosquitto/configinc
      accessMode: ReadWriteOnce
      size: 100Mi
