apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: "{{ $fullname }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: "{{ $fullname }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ $fullname }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy | default "IfNotPresent" }}"
        ports:
        - containerPort: {{ .Values.service.port | int }}
        - containerPort: {{ .Values.service.securePort | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port | int }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
