apiVersion: v1
kind: Secret
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: "{{ $fullname }}-secret"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  {{- if not .Values.config.authentication.usersSecret }}
  pwfile: |
    {{- range $key, $value := .Values.config.authentication.users }}
    {{ $key }}:{{ $value }}
    {{- end }}
  {{- end }}
