{{- if and .Values.config.enableSecure (not .Values.config.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: "{{ $fullname }}-tls-secret"
  namespace: "{{ .Release.Namespace }}"
type: kubernetes.io/tls
data:
  {{- if .Values.config.tls.cafile }}
  ca.crt: {{ .Values.config.tls.cafile | b64enc }}
  {{- end }}
  {{- if .Values.config.tls.certfile }}
  tls.crt: {{ .Values.config.tls.certfile | b64enc }}
  {{- end }}
  {{- if .Values.config.tls.keyfile }}
  tls.key: {{ .Values.config.tls.keyfile | b64enc }}
  {{- end }}
{{- end }}
